/*
 *   Copyright (c) 2024 Arcology Network

 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.

 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.

 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package scheduler

import (
	"math"
	"sort"

	"github.com/arcology-network/common-lib/codec"
	associative "github.com/arcology-network/common-lib/exp/associative"
	mapi "github.com/arcology-network/common-lib/exp/map"
	"github.com/arcology-network/common-lib/exp/slice"

	slices "github.com/arcology-network/common-lib/exp/slice"
	eucommon "github.com/arcology-network/common-lib/types"
	stgcommon "github.com/arcology-network/storage-committer/common"
	"github.com/arcology-network/storage-committer/type/univalue"
)

type Scheduler struct {
	calleeDict map[string]uint32 // A calleeDict table to find the index of a calleeDict by its address + signature.
	callees    []*Callee         // For deterministic scheduling results!!!!
}

// Initialize a new scheduler, the fildb is the file path to the scheduler's conflict database and the deferByDefault
// instructs the scheduler to schedule the deferred transactions if it is true.
func NewScheduler(fildb string, deferByDefault bool) (*Scheduler, error) {
	return &Scheduler{
		calleeDict: make(map[string]uint32),
	}, nil
}

// Import callee information from the given property transitions generated by the EUs.
func (this *Scheduler) Import(propertyTransitions []*univalue.Univalue) {
	for _, v := range propertyTransitions {
		if v.GetPath() == nil {
			continue
		}
		_, addr, sign := new(Callee).parseCalleeSignature(*v.GetPath())
		if len(addr) == 0 || len(sign) == 0 {
			continue
		}
		_, callee := this.Find(codec.Bytes20{}.FromBytes(addr[:]), codec.Bytes4{}.FromBytes(sign[:]))
		callee.init(v)
	}
}

// The function will find the index of the entry by its address and signature.
// If the entry is found, the index will be returned. If the entry is not found, the index will be added to the scheduler.
func (this *Scheduler) Find(addr [20]byte, sig [4]byte) (uint32, *Callee) {
	lftKey := string(append(addr[:stgcommon.SHORT_CONTRACT_ADDRESS_LENGTH], sig[:]...)) // Join the address and signature to create a unique key.
	idx, ok := this.calleeDict[lftKey]
	if !ok {
		idx = uint32(len(this.callees))
		this.callees = append(this.callees, NewCallee(idx, addr[:], sig[:]))
		this.calleeDict[lftKey] = idx
	}
	return idx, this.callees[idx]
}

// Add a conflict pair to the scheduler
func (this *Scheduler) Add(lftAddr [20]byte, lftSig [4]byte, rgtAddr [20]byte, rgtSig [4]byte) bool {
	lftIdx, lftCallee := this.Find(lftAddr, lftSig)
	rgtIdx, rgtCallee := this.Find(rgtAddr, rgtSig)

	if lftCallee.IsInConflictList(rgtIdx) && rgtCallee.IsInConflictList(lftIdx) {
		return false // Recorded already
	}

	// If doesn't exist, add the conflict pair to the scheduler.
	if !slices.Contains(this.callees[lftIdx].Indices, rgtIdx, func(a uint32, b uint32) bool {
		return a == b
	}) {
		this.callees[lftIdx].Indices = append(this.callees[lftIdx].Indices, rgtIdx)
	}

	if !slices.Contains(this.callees[rgtIdx].Indices, lftIdx, func(a uint32, b uint32) bool {
		return a == b
	}) {
		this.callees[rgtIdx].Indices = append(this.callees[rgtIdx].Indices, lftIdx)
	}
	return true
}

// Add a deferred function to the scheduler.
func (this *Scheduler) AddDeferred(addr [20]byte, funSig [4]byte) {
	idx, _ := this.Find(addr, funSig)
	this.callees[idx].Deferrable = true
}

// The scheduler will optimize the given transactions and return a schedule.
// The schedule will contain the transactions that can be executed in parallel and the ones that have to
// be executed sequentially.
func (this *Scheduler) New(stdMsgs []*eucommon.StandardMessage) *Schedule {
	// Get the static schedule for the given transactions first.
	sch, pendingMsgs := this.StaticSchedule(stdMsgs) // The pendingMsgs are the transactions that need to be scheduled to avoid conflicts.
	if len(pendingMsgs) == 0 {
		return sch // No known conflicts and no deferred transactions.
	}

	// Sort the callees by the number of conflicts and the callee index in ascending order.
	// Need to use pairs not pendingMsgs
	sort.Slice(pendingMsgs, func(i, j int) bool {
		lft, rgt := len(this.callees[(pendingMsgs)[i].First].Indices), len(this.callees[(pendingMsgs)[j].First].Indices)
		if lft < rgt {
			return lft < rgt
		}
		return (pendingMsgs)[i].Second.ID < (pendingMsgs)[j].Second.ID
	})

	// The code below will search for the parallel transaction set from a set of conflicting transactions.
	// Whataever left is the sequential transaction set after this.
	for {
		// The conflict dictionary of all indices of the current transaction set.
		seedCallee := *slice.PopFront(&pendingMsgs)
		paraMsgs := associative.Pairs[uint32, *eucommon.StandardMessage]{seedCallee} // A set of conflict free transactions, starting with the first callee.

		// Load the conflict dictionary with the conflicts of the FIRST callee, from which the search will start.
		// Add the first callee's conflicts to the conflict dictionary.
		blacklist := mapi.FromSlice(this.callees[seedCallee.First].Indices, func(k uint32) bool { return true })
		paraMsgIds := mapi.FromSlice(paraMsgs.Firsts(), func(_ uint32) bool {
			return true
		})
		// Look for the parallel transactions that aren't conflicting with the current set of transactions.
		for i := 0; i < len(pendingMsgs); i++ {
			targetMsg := pendingMsgs[i]

			// The current callee isn't conflicting with any transaction in the unique callee set
			if !blacklist[targetMsg.First] && !mapi.ContainsAny(paraMsgIds, this.callees[targetMsg.First].Indices) {
				// Add the new callee's conflicts to the conflict dictionary.
				mapi.Insert(blacklist, this.callees[targetMsg.First].Indices, func(_ int, k uint32) (uint32, bool) {
					return k, true
				})

				paraMsgs = append(paraMsgs, targetMsg) // Add the current callee to the parallel transaction set.
				paraMsgIds[targetMsg.First] = true
				slice.RemoveAt(&pendingMsgs, i) // Remove the current callee, since it is already in the parallel set.
				i--
			}
		}

		// One transaction, no need to continue.
		if len(paraMsgs) == 1 {
			sch.WithConflict = append(sch.WithConflict, paraMsgs.Seconds()...)
			break
		}

		// Look for the deferred transactions and add them to the deferred transaction set.
		deferredGen := this.ScheduleDeferred(&paraMsgs)

		paraGen := slices.Transform(paraMsgs.Seconds(), func(i int, v *eucommon.StandardMessage) []*eucommon.StandardMessage {
			return []*eucommon.StandardMessage{v}
		})

		sch.Generations = append(sch.Generations, paraGen)
		sch.Generations = append(sch.Generations, deferredGen) // Insert the parallel transaction first

		// Remove the already schedule transaction from the pendingMsgs slice.
		if len(pendingMsgs) == 0 {
			break // Nothing left to process.
		}
	}

	// Deferred array can be empty, so remove it if it is.
	slice.RemoveIf(&sch.Generations, func(i int, stdMsgs [][]*eucommon.StandardMessage) bool {
		return len(stdMsgs) == 0
	})

	// Whatever left in the pendingMsgs array is the sequential transaction set.
	sch.WithConflict = append(sch.WithConflict, (*associative.Pairs[uint32, *eucommon.StandardMessage])(&pendingMsgs).Seconds()...)
	return sch
}

// The scheduler will scan through and look for multipl instances of the same callee and put one of them in the second
// consecutive set of transactions for deferred execution.
func (this *Scheduler) ScheduleDeferred(paraMsgInfo *associative.Pairs[uint32, *eucommon.StandardMessage]) [][]*eucommon.StandardMessage {
	sort.SliceStable(*paraMsgInfo, func(i, j int) bool {
		if (*paraMsgInfo)[i].First != (*paraMsgInfo)[j].First {
			return (*paraMsgInfo)[i].First < (*paraMsgInfo)[j].First
		}
		return (*paraMsgInfo)[i].Second.ID < (*paraMsgInfo)[j].Second.ID
	})

	array := ([]*associative.Pair[uint32, *eucommon.StandardMessage])(*paraMsgInfo)
	_, msgSets := slice.GroupBy(array, func(i int, pair *associative.Pair[uint32, *eucommon.StandardMessage]) *string {
		v := string(Compact(pair.Second.Native.To[:], pair.Second.Native.Data[:]))
		return &v
	})

	// Remove single instances or non-deferable ones.
	slice.RemoveIf(&msgSets, func(i int, pairs []*associative.Pair[uint32, *eucommon.StandardMessage]) bool {
		return len(pairs) == 1 || !pairs[0].Second.IsDeferred
	})

	deferredGen := [][]*eucommon.StandardMessage{} // The deferred transaction generation.
	for _, msgs := range msgSets {
		def := *slice.PopBack(&msgs)
		deferredGen = append(deferredGen, []*eucommon.StandardMessage{def.Second}) // Add the deferred transaction to the new generation.
	}
	return deferredGen
}

// The scheduler will StaticSchedule base on some predefined rules for specific transaction types.
func (this *Scheduler) StaticSchedule(stdMsgs []*eucommon.StandardMessage) (*Schedule, []*associative.Pair[uint32, *eucommon.StandardMessage]) {
	sch := &Schedule{}
	if len(stdMsgs) == 0 {
		return sch, []*associative.Pair[uint32, *eucommon.StandardMessage]{} // No transactions to process.
	}

	// Transfers won't have any conflicts, as long as they have enough balances. Deployments are less likely to have conflicts, but it's not guaranteed.
	sch.Transfers = slice.MoveIf(&stdMsgs, func(i int, msg *eucommon.StandardMessage) bool { return len(msg.Native.Data) == 0 })
	sch.Deployments = slice.MoveIf(&stdMsgs, func(i int, msg *eucommon.StandardMessage) bool { return msg.Native.To == nil })

	if len(stdMsgs) == 0 {
		return sch, []*associative.Pair[uint32, *eucommon.StandardMessage]{} // All the transactions are transfers.
	}

	// Get the IDs for the given addresses and signatures, which will be used to find the callee index.
	// To save memory, the callees are stored in the dictionary by their IDs, not by their addresses and signatures.
	pairs := slice.ParallelTransform(stdMsgs, 8, func(i int, msg *eucommon.StandardMessage) *associative.Pair[uint32, *eucommon.StandardMessage] {

		// Convert the address and signature to a unique key.
		key := Compact((*msg.Native.To)[:], msg.Native.Data[:])
		idx, ok := this.calleeDict[string(key)] // Check if the key is already in the calleeDict.
		if !ok {
			idx = math.MaxUint32 // The callee is new, no known conflicts.
		}
		return &associative.Pair[uint32, *eucommon.StandardMessage]{First: idx, Second: stdMsgs[i]}
	})

	if len(pairs) == 0 {
		return sch, pairs
	}

	// Move the transactions that have no known conflicts to the parallel trasaction array first.
	// If a callee has no known conflicts with anyone else, it is either a conflict-free implementation or
	// has been fortunate enough to avoid conflicts so far.
	unknows := slice.MoveIf(&pairs, func(_ int, v *associative.Pair[uint32, *eucommon.StandardMessage]) bool {
		return v.First == math.MaxUint32
	})
	sch.Unknowns = (*associative.Pairs[uint32, *eucommon.StandardMessage])(&unknows).Seconds()

	// Deployments are less likely to have conflicts, but it's not guaranteed.
	sequentialOnly := slice.MoveIf(&pairs, func(_ int, v *associative.Pair[uint32, *eucommon.StandardMessage]) bool {
		if v.First < uint32(len(this.callees)) {
			return this.callees[v.First].Sequential
		}
		return false
	})
	sch.Unknowns = (*associative.Pairs[uint32, *eucommon.StandardMessage])(&unknows).Seconds()
	sch.Sequentials = (*associative.Pairs[uint32, *eucommon.StandardMessage])(&sequentialOnly).Seconds()

	return sch, pairs
}
