/*
 *   Copyright (c) 2024 Arcology Network

 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.

 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.

 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package scheduler

import (
	"math"
	"sort"

	"github.com/arcology-network/common-lib/codec"
	assoc "github.com/arcology-network/common-lib/exp/associative"
	mapi "github.com/arcology-network/common-lib/exp/map"
	"github.com/arcology-network/common-lib/exp/orderedmap"
	"github.com/arcology-network/common-lib/exp/slice"

	slices "github.com/arcology-network/common-lib/exp/slice"
	eucommon "github.com/arcology-network/common-lib/types"
	"github.com/arcology-network/storage-committer/type/univalue"

	profile "github.com/arcology-network/scheduler/profiles"
	workload "github.com/arcology-network/scheduler/workload"
)

type Scheduler struct {
	fileName     string
	profileDict  *orderedmap.OrderedMap[uint64, uint64, *profile.CalleeProfile]
	contractDict *orderedmap.OrderedMap[[20]byte, uint32, *profile.ContractInfo]
}

// Initialize a new scheduler, the fileName is the file path to the scheduler's conflict database and the deferByDefault
// instructs the scheduler to schedule the deferred transactions if it is true.
func NewScheduler(fileName string) (*Scheduler, error) {
	contractDict := orderedmap.NewOrderedMap(
		nil,
		10,
		func(key [20]byte, funcIdx uint32) *profile.ContractInfo {
			return &profile.ContractInfo{
				Address: key,
				FuncIdx: []uint32{funcIdx},
			}
		},

		func(key [20]byte, funcIdx uint32, profile **profile.ContractInfo) {
			(*profile).FuncIdx = append((*profile).FuncIdx, funcIdx)
		},
	)

	profileDict := orderedmap.NewOrderedMap(
		nil,
		10,
		func(key uint64, _ uint64) *profile.CalleeProfile {
			return &profile.CalleeProfile{
				UID: key,
			}
		},
		func(_ uint64, _ uint64, profile **profile.CalleeProfile) {},
	)

	return &Scheduler{
		fileName:     fileName,
		profileDict:  profileDict,
		contractDict: contractDict,
	}, nil
}

// To get the number of profiles in the scheduler.
func (this *Scheduler) Length() int {
	return this.profileDict.Length()
}

// LoadIn the given callees into the scheduler.
func (this *Scheduler) LoadIn(callees []*profile.CalleeProfile) {
	UIDs := slice.ParallelTransform(callees, 4, func(i int, callee *profile.CalleeProfile) uint64 {
		return callee.UID
	})
	this.profileDict.CopyFrom(UIDs, callees)
}

// Import profile information from the given property transitions generated by the EUs.
// The info could contain things like::
// 1. Conflict info between different callees.
// 2. Deferred function info.
// 3. Sequential only function info.
// 4. Max gas limit info.
func (this *Scheduler) Import(profileTrans []*univalue.Univalue) {
	for _, v := range profileTrans {
		if v.GetPath() == nil {
			continue
		}

		// package and variable name mixed use
		_, addr, selector := new(profile.CalleeProfile).ParseKeyFromPath(*v.GetPath())
		if len(addr) == 0 || len(selector) == 0 {
			continue
		}
		profr, _ := this.GetOrCreateProfile(codec.Bytes20{}.FromBytes(addr[:]), codec.Bytes4{}.FromBytes(selector[:]))
		profr.Init(v)
	}
}

func (this *Scheduler) GetOrCreateProfile(addr [20]byte, selector [4]byte) (*profile.CalleeProfile, uint32) {
	key := profile.DeriveUID(addr[:], selector[:])
	callee, idx, exists := this.profileDict.Get(key) // Ensure the profile is created.
	if exists {
		return callee, uint32(idx)
	}

	// Create a new profile entry and return its index.
	callee, idx = this.profileDict.Set(key, math.MaxUint64)
	return callee, uint32(idx)
}

// Register a conflict pair into the scheduler.
func (this *Scheduler) RegisterConflict(lftAddr [20]byte, lftSig [4]byte, rgtAddr [20]byte, rgtSig [4]byte) bool {
	seedCallee, lftIdx := this.GetOrCreateProfile(lftAddr, lftSig)
	rgtCallee, rgtIdx := this.GetOrCreateProfile(rgtAddr, rgtSig)

	if seedCallee.IsInConflictList(rgtIdx) && rgtCallee.IsInConflictList(lftIdx) {
		return false // Recorded already
	}

	// If doesn't exist, add the conflict pair to the scheduler.
	if !slices.Contains(seedCallee.ConflictWith, rgtIdx, func(a uint32, b uint32) bool {
		return a == b
	}) {
		seedCallee.ConflictWith = append(seedCallee.ConflictWith, rgtIdx)
	}

	if !slices.Contains(rgtCallee.ConflictWith, lftIdx, func(a uint32, b uint32) bool {
		return a == b
	}) {
		rgtCallee.ConflictWith = append(rgtCallee.ConflictWith, lftIdx)
	}
	return true
}

// Add a deferred function to the scheduler.
func (this *Scheduler) AddDeferred(addr [20]byte, selector [4]byte) {
	callee, _ := this.GetOrCreateProfile(addr, selector)
	callee.Deferrable = true
}

// The scheduler will optimize the given transactions and return a schedule.
// The schedule will contain the transactions that can be executed in parallel and the ones that have to
// be executed sequentially.
func (this *Scheduler) New(stdMsgs []*eucommon.StandardMessage) *workload.Schedule {
	// Get the static schedule for the given transactions first.
	sch, pendingMsgs := this.StaticSchedule(stdMsgs) // The pendingMsgs are the transactions that need to be scheduled to avoid conflicts.
	if len(pendingMsgs) == 0 {
		return sch // No known conflicts and no deferred transactions.
	}

	// Sort the callees by the number of conflicts and the profile index in ascending order.
	// Need to use pairs not pendingMsgs
	sort.Slice(pendingMsgs, func(i, j int) bool {
		_, lft := this.profileDict.At(int((pendingMsgs)[i].First))
		_, rgt := this.profileDict.At(int((pendingMsgs)[j].First))

		if len(lft.ConflictWith) != len(rgt.ConflictWith) {
			return len(lft.ConflictWith) < len(rgt.ConflictWith)
		}
		return lft.Idx < rgt.Idx
	})

	// The code below will search for the parallel transaction set from a set of conflicting transactions.
	// Whataever left is the sequential transaction set after this.
	for {
		// The conflict dictionary of all indices of the current transaction set.
		seedMsg := *slice.PopFront(&pendingMsgs)
		paraMsgs := assoc.Pairs[uint32, *eucommon.StandardMessage]{seedMsg} // A set of conflict free transactions, starting with the first profile.

		// Load the conflict dictionary with the conflicts of the FIRST profile, from which the search will start.
		// Add the first profile's conflicts to the conflict dictionary.
		_, seedCallee := this.profileDict.At(int(seedMsg.First))
		lftConflictList := mapi.FromSlice(seedCallee.ConflictWith, func(k uint32) bool { return true })
		paraMsgIds := mapi.FromSlice(paraMsgs.Firsts(), func(_ uint32) bool {
			return true
		})

		// Look for the parallel transactions that aren't conflicting with the current set of transactions.
		for i := 0; i < len(pendingMsgs); i++ {
			targetMsg := pendingMsgs[i]

			// The current profile isn't conflicting with any transaction in the unique profile set
			_, rgtCallee := this.profileDict.At(int(targetMsg.First))
			if !lftConflictList[targetMsg.First] && !mapi.ContainsAny(paraMsgIds, rgtCallee.ConflictWith) {
				// Add the new profile's conflicts to the conflict dictionary.
				mapi.Insert(lftConflictList, rgtCallee.ConflictWith, func(_ int, k uint32) (uint32, bool) {
					return k, true
				})

				paraMsgs = append(paraMsgs, targetMsg) // Add the current profile to the parallel transaction set.
				paraMsgIds[targetMsg.First] = true
				slice.RemoveAt(&pendingMsgs, i) // Remove the current profile, since it is already in the parallel set.
				i--
			}
		}

		// One transaction, no need to continue.
		if len(paraMsgs) == 1 {
			sch.WithConflict = append(sch.WithConflict, paraMsgs.Seconds()...)
			break
		}

		// Look for the deferred transactions and add them to the deferred transaction set.
		deferredGen := this.ScheduleDeferred(&paraMsgs)

		paraGen := slices.Transform(paraMsgs.Seconds(), func(i int, v *eucommon.StandardMessage) []*eucommon.StandardMessage {
			return []*eucommon.StandardMessage{v}
		})

		sch.MsgSet = append(sch.MsgSet, paraGen)
		sch.MsgSet = append(sch.MsgSet, deferredGen) // Insert the parallel transaction first

		// new(workload.JobSequence).FromStandardMessages(0, paraGen)

		// Remove the already schedule transaction from the pendingMsgs slice.
		if len(pendingMsgs) == 0 {
			break // Nothing left to process.
		}
	}

	// Whatever left in the pendingMsgs array is the sequential transaction set.
	sch.WithConflict = append(sch.WithConflict, (*assoc.Pairs[uint32, *eucommon.StandardMessage])(&pendingMsgs).Seconds()...)
	return sch
}

// The scheduler will scan through and look for multipl instances of the same profile and put one of them in the second
// consecutive set of transactions for deferred execution.
func (this *Scheduler) ScheduleDeferred(paraMsgInfo *assoc.Pairs[uint32, *eucommon.StandardMessage]) [][]*eucommon.StandardMessage {
	sort.SliceStable(*paraMsgInfo, func(i, j int) bool {
		if (*paraMsgInfo)[i].First != (*paraMsgInfo)[j].First {
			return (*paraMsgInfo)[i].First < (*paraMsgInfo)[j].First
		}
		return (*paraMsgInfo)[i].Second.ID < (*paraMsgInfo)[j].Second.ID
	})

	array := ([]*assoc.Pair[uint32, *eucommon.StandardMessage])(*paraMsgInfo)
	_, msgSets := slice.GroupBy(array, func(i int, pair *assoc.Pair[uint32, *eucommon.StandardMessage]) *string {
		key := profile.DeriveKey(pair.Second.Native.To[:], pair.Second.Native.Data[:])
		v := string(key[:])
		return &v
	})

	// Remove single instances or non-deferable ones.
	slice.RemoveIf(&msgSets, func(i int, pairs []*assoc.Pair[uint32, *eucommon.StandardMessage]) bool {
		return len(pairs) == 1 || !pairs[0].Second.IsDeferred
	})

	deferredGen := [][]*eucommon.StandardMessage{} // The deferred transaction generation.
	for _, msgs := range msgSets {
		def := *slice.PopBack(&msgs)
		deferredGen = append(deferredGen, []*eucommon.StandardMessage{def.Second}) // Add the deferred transaction to the new generation.
	}
	return deferredGen
}

// The scheduler will StaticSchedule base on some predefined rules for specific transaction types,
// such as transfers and contract deployments.
func (this *Scheduler) StaticSchedule(stdMsgs []*eucommon.StandardMessage) (*workload.Schedule, []*assoc.Pair[uint32, *eucommon.StandardMessage]) {
	sch := &workload.Schedule{}
	if len(stdMsgs) == 0 {
		return sch, []*assoc.Pair[uint32, *eucommon.StandardMessage]{} // No transactions to process.
	}

	// Transfers won't have any conflicts, as long as they have enough balances.
	// Deployments are conflict-free as well.
	sch.Transfers = slice.MoveIf(&stdMsgs, func(i int, msg *eucommon.StandardMessage) bool { return len(msg.Native.Data) == 0 })
	sch.Deployments = slice.MoveIf(&stdMsgs, func(i int, msg *eucommon.StandardMessage) bool { return msg.Native.To == nil })

	if len(stdMsgs) == 0 {
		return sch, []*assoc.Pair[uint32, *eucommon.StandardMessage]{} // All the transactions are transfers.
	}

	// Get the IDs for the given addresses and signatures, which will be used to find the profile index.
	// To save memory, the callees are stored in the dictionary by their IDs, not by their addresses and signatures.
	msgProfiles := slice.ParallelTransform(stdMsgs, 8, func(i int, msg *eucommon.StandardMessage) *assoc.Pair[uint32, *eucommon.StandardMessage] {
		// Convert the address and signature to a unique key.
		uid := profile.DeriveUID((*msg.Native.To)[:], msg.Native.Data[:])
		_, idx, ok := this.profileDict.Get(uid) // Check if the key is already in the calleeDict.
		if !ok {
			idx = math.MaxUint32 // The profile is new, no known conflicts.
		}
		return &assoc.Pair[uint32, *eucommon.StandardMessage]{First: uint32(idx), Second: stdMsgs[i]}
	})

	if len(msgProfiles) == 0 {
		return sch, msgProfiles
	}

	// Move the transactions that have no known conflicts to the parallel trasaction array first.
	// If a profile has no known conflicts with anyone else, it is either a conflict-free implementation or
	// has been fortunate enough to avoid conflicts so far.
	unknows := slice.MoveIf(&msgProfiles, func(_ int, v *assoc.Pair[uint32, *eucommon.StandardMessage]) bool {
		return v.First == math.MaxUint32
	})
	sch.Unknowns = (*assoc.Pairs[uint32, *eucommon.StandardMessage])(&unknows).Seconds()

	// Deployments are conflict free as well.
	sequentialOnly := slice.MoveIf(&msgProfiles, func(_ int, v *assoc.Pair[uint32, *eucommon.StandardMessage]) bool {
		// The profile isn't new, otherwise the v.First would be math.MaxUint32.
		if v.First < uint32(this.profileDict.Length()) {
			_, profile := this.profileDict.At(int(v.First))
			return profile.Sequential
		}
		return false
	})
	sch.Unknowns = (*assoc.Pairs[uint32, *eucommon.StandardMessage])(&unknows).Seconds()
	sch.Sequentials = (*assoc.Pairs[uint32, *eucommon.StandardMessage])(&sequentialOnly).Seconds()

	return sch, msgProfiles
}
